[package]
name = "aoc"
version = "2022.0.0"
edition = "2021"

[dependencies]

[[bin]]
name = "day01"
path = "./src/day01.rs"

[[bin]]
name = "day02"
path = "./src/day02.rs"

[[bin]]
name = "day03"
path = "./src/day03.rs"
